dataiku/dataiku-api-client-python

dataikuapi/dss/apideployer.py
Add a method to map on API deployer infrastructure creation call.
=> Add API deployer infra creation

dataikuapi/dss/project.py, dataikuapi/dss/projectfolder.py, dataikuapi/dssclient.py
[branch ch35668]
https://app.clubhouse.io/dataiku/story/35668/make-project-folders-a-backend-object
https://analytics.dataiku.com/projects/RDWIKI/wiki/Dev%20Project%201:%20Make%20Project%20Folders%20a%20backend%20object
=> Project folder backend object (dev prj~1)

dataikuapi/dss/ml.py, dataikuapi/utils.py
This PR replaces `DSSInternalDict` (which did not have a lot of features) to use an `_internal_dict` object in each subclass.
=> utils: remove DSSInternalDict

module_utils/dataikuapi
This small change looks like nothing, but it makes this repo a valid ansible role able to provide `module_utils` to other roles.
This should not have any impact on DSS since only `dataikuapi` is shipped.
=> misc: Make this repo a valid ansible role

dataikuapi/dss/job.py, dataikuapi/dss/macro.py, dataikuapi/dss/project.py, dataikuapi/dss/scenario.py, dataikuapi/dss/wiki.py
Other modules use relative imports for this file.
This change is required to have the API shipped as `module_utils` in Ansible use cases.
=> imports: Use relative imports as in other modules

dataikuapi/dss/savedmodel.py
Adding a `delete_versions` method to `DSSSavedModel`.
See https://github.com/dataiku/dip/pull/10513 for background.
=> Adding delete_versions to the saved model API.

dataikuapi/dss/ml.py
Required for the DKU App to be able to use python API to remap ML task's target without changing the rest of the settings
Linked to https://github.com/dataiku/dip/pull/10681
=> Added redetect flag to ML task guess public API

meta/main.yml
This makes the package installable by `ansible-galaxy` directly.
=> Add Ansible Galaxy metadata.

dataikuapi/dss/ml.py, dataikuapi/dss/savedmodel.py, dataikuapi/dss/utils.py
[ch47819](https://app.clubhouse.io/dataiku/story/47819/api-to-get-source-analysis-from-saved-model-version) The goal here is to mimic the two buttons in the UI "View original analysis". 
The first on is located in the saved model page (where the list of versions are) and it redirects to the last exported ML task.
The second is located in the saved model version page and it redirects to the origin trained model of this version (either if it has been export or either if it has been retraining )
Add two methods to facilitate navigation from saved model's objects to analysis' objects:
- for getting the origin mltask of a saved model:
```python
mltask:DSSMLTask = saved_model.get_origin_ml_task()
```
- for getting the origin trained model of a saved model version:
```python …
```
=> Add two methods to facilitate navigation from SM's objects to analysis' objects

dataikuapi/dss/savedmodel.py
[ch47819](https://app.clubhouse.io/dataiku/story/47819/api-to-get-source-analysis-from-saved-model-version): Use the modern API pattern for `DSSSavedModel` by replacing the `get_definition`  by a new class: `DSSSavedModelSettings` and its method `get_raw`
=> Add DSSSavedModelSettings class

dataikuapi/dss/app.py, dataikuapi/dss/continuousactivity.py, dataikuapi/dss/plugin.py, dataikuapi/dss/savedmodel.py
Like previous changes in release/7.0, keeping consistency with the fact imports are relative is required not to brake ansible usability.
=> Add relative imports

dataikuapi/dssclient.py
[ch53225](https://app.clubhouse.io/dataiku/story/53225/dataikuapi-does-not-provide-download-plugin)
=> Adding download_plugin_stream and download_plugin_to_file to dataikuapi.

dataikuapi/dss/project.py
[ch55158](https://app.clubhouse.io/dataiku/story/55158/project-settings-api-for-set-python-code-env-and-set-r-code-env-don-t-work-on-8-0-anymore)
=> Fix helpers to set code env: env mode was not set

dataikuapi/dss/project.py
Now you can manually choose which scenarios are automatically enabled/disabled at the same time as activating a bundle.
=> Add scenario enabling to bundle activation

dataikuapi/dss/apideployer.py, dataikuapi/dss/projectdeployer.py, dataikuapi/dssclient.py
[ch47130](https://app.clubhouse.io/dataiku/story/47130/public-api-for-project-deployer)
See PR for the Public API on dip: https://github.com/dataiku/dip/pull/11101
=> Add Python client for Project deployer

dataikuapi/dss/future.py
Story details: [ch56069](https://app.clubhouse.io/dataiku/story/56069)
When the backend response is very fast to be computed, the initial response to the api call already contains the result, and does not contain a jobId.
This leads to the calls to get updates on the future to fail (no jobId)
The fix is to verify that the state does not already contain the result before an update.
=> Verify that the state does not already contain the result.

dataikuapi/dss/wiki.py
[ch55059](https://app.clubhouse.io/dataiku/story/55059)
Need an instance with at least [dip#11418](https://github.com/dataiku/dip/pull/11418) merged (not on master yet)
=> Add functions to export a wiki article as a PDF

dataikuapi/dss/ml.py
First draft of methods to be added is in the [wiki](https://analytics.dataiku.com/projects/RDWIKI/wiki/972/Feature:%20ML%20assertions#public-api-1)
Can be tested with the [dip pr](https://github.com/dataiku/dip/pull/11515) that adds tests for the methods added in this PR.
=> Add assertions public api methods

dataikuapi/dss/recipe.py
The `DSSRecipe.run` method fails for (prediction and clustering) training recipes, because the recipe output type is not correctly set to `"SAVED_MODEL"`, hence interpreted as a dataset.
If the recipe to run is a training recipe, correctly set the output type to `"SAVED_MODEL"`
[ch54893]
=> Set output type to correct value when running training recipe

dataikuapi/dss/analysis.py, dataikuapi/dss/dataset.py, dataikuapi/dss/ml.py, dataikuapi/dss/project.py
See [ch59584](https://app.clubhouse.io/dataiku/story/59584)
This PR:
* adds better support for plugin & custom algorithms in the ML helpers, in particular when listing & getting algorithm settings
* adds support for `wait_guess_complete` when creating clustering ML Task, to align with prediction MLTasks for which it is already available, and changes the default behavior to `wait_guess_complete=True`, which is what we want in the vast majority of cases
* fixes a few things found while testing:
* no fail if "plugin_python" key not in modeling, for clustering task when `disable_all_algorithms`
* only register "impurity" for MLlib Random Forest, duplication previously broke instantiation of the algorithm settings
=> Better suport custom & plugin algos

dataikuapi/dss/notebook.py, dataikuapi/dss/project.py
Story details : [[ch56395]](https://app.clubhouse.io/dataiku/story/56395)
=> Python wrapper for Jupyter Notebooks Public API

dataikuapi/dss/apideployer.py, dataikuapi/dss/project.py, dataikuapi/dss/projectdeployer.py, dataikuapi/utils.py
[ch59800](https://app.clubhouse.io/dataiku/story/59800/feedback-on-apis-for-pdpl)
A PR is opened to add the API in the doc: https://github.com/dataiku/dss-doc/pull/458
- Move and rename `DSSProjectDeployerProject#import_bundle` (to `DSSProjectDeployer#upload_bundle`)
- Do not pass design node info as params anymore
- Pass the published key as a param (to match what we do in the UI)
- `DSSProjectDeployerDeploymentSettings`: add a property `bundle_id`
- Add a `DSSProjectDeployerProjectStatus#get_deployments` method
- Add wrapper classes for infra (`DSSProjectDeployerInfraStatus`/`DSSAPIDeployerInfraStatus`)
- ~`DSSAPIDeployerInfra#get_status`/`DSSAPIDeployerInfra#get_status` corresponding public API calls are implemented in https://github.com/dataiku/dip/pull/12012~ (now merged)
- Add a …
=> Project deployer: update some PDPL methods

dataikuapi/dss/project.py
The API was finished, so let's remove these warnings.
=> Remove unwanted warning in the python doc.

dataikuapi/dss/project.py
Change the parameter to use snake case instead of camel case (more pythonic and in consistent with other parameters).
Part of [ch62224](https://app.clubhouse.io/dataiku/story/62224/api-to-get-project-creation-and-last-modification-date).
=> project: change get_timeline() item_count param

dataikuapi/dss/scenario.py
[[ch63893]](https://app.clubhouse.io/dataiku/story/63893/bug-in-public-api-for-scenario-triggers-add-monthly-trigger-add-periodic-trigger)
Time Triggers have new capabilities, let's add them to the python API.
~Associated PR: https://github.com/dataiku/dip/pull/12548~
=> Improve time trigger Python API [ch63893]

dataikuapi/dssclient.py
Using the json encoder manage for us the encoding/decoding on sender
receiver.
[[ch63983]](https://app.clubhouse.io/dataiku/story/63983/unable-to-set-license-via-api-if-it-contains-chinese-characters)
=> Fix set_license with utf-8 chars

dataikuapi/dss/dataset.py
[ch63230]  autodetect ES dataset for python client users, this allows to reproduce the DSS user experience programmatically
Makes it now possible to create and test an ES dataset by inferring schema:
new_es_ds = project.create_dataset(name, "ElasticSearch", params)
new_es_ds_settings = new_es_ds.autodetect_settings()
new_es_ds_settings.save()
=> [ch63230] enable ES datasets autodetect

dataikuapi/dss/ml.py
Story details : [[ch58204]](https://app.clubhouse.io/dataiku/story/58204)
⚠️ use and merge with https://github.com/dataiku/dip/pull/12168
=> MDG Public API python wrapper

dataikuapi/dssclient.py
[ch58301]
no helper object, since it wouldn't bring much compared to just accessing fields in the object
=> add call to grab usage summary

dataikuapi/dss/ml.py
See [ch67573](https://app.clubhouse.io/dataiku/story/67573/support-the-lightgbm-algorithm-in-the-public-api)
While playing with the API I noticed that exposing the LightGBM hyperparameters was not implemented.
=> Include LightGBM to the list of ML algorithms in the public API

dataikuapi/dss/apideployer.py
- added a governance check policy flag on API Deployer infrastructures
- added endpoint to check governance status of a deployment (current versions selected) or possiblity to choose a specific versionId from its related "published api service" 
- added ignoreWarnings flag on deployment action / switch version action endpoints to fit backend endpoints (depending on infra governance policy : prevent / warn / no_check, and the governance status of the related model version(s), throw an exception of run smoothly)
=> Govern integration in DSS

dataikuapi/dss/apideployer.py
In the API Deployer, deleting a Deployment that is in the `enabled` state (i.e. deployed on an Infrastructure) _without disabling it first_ will remove the Deployment from the UI _but not from the Infrastructure_. This is problematic since users may have to deal with dangling deployments on their Infrastructure(s) not visible on the UI anymore.
This PR introduces a safer way to programmatically delete a Deployment, by first checking if it is enabled, and then:
- disabling the Deployment if the `force` flag is set to `True`,
- throwing an exception prompting the user to disable the Deployment if `force` is set to `False`.
=> Clean deletion process for APIDeployerDeployment

dataikuapi/dss/admin.py, dataikuapi/dssclient.py
PR associated with the change https://github.com/dataiku/dip/pull/13218
=> [ch58209] Add personal API keys APIs

dataikuapi/dss/ml.py, dataikuapi/dss/project.py
This PR adds two calls to the python API:
- `train_queue` - Starts running the queue of the ML task
- `list_mltask_queues` - Lists all the existing ML tasks in a project
[ch63630]
=> ML Task Queues - Train queue + list queues

dataikuapi/dss/ml.py, dataikuapi/dss/modelevaluationstore.py
Relates to https://github.com/dataiku/dip/pull/13469
=> Added a method to compute data drift on a ME

dataikuapi/__init__.py, dataikuapi/fm/future.py, dataikuapi/fm/instances.py, dataikuapi/fm/instancesettingstemplates.py, dataikuapi/fm/tenant.py, dataikuapi/fm/virtualnetworks.py, dataikuapi/fmclient.py
=> Add python client for FM API

dataikuapi/fm/instances.py, dataikuapi/fmclient.py
As I was testing the API against Azure, I found another issue around the volumes encryption. Nothin very hard to fix at the end, just the mapping of the model was incorrect.
Note that is is targeted for 10.0.1 for now
```
./fmadmin create-personal-api-key admin fm-api-key.txt
```
Then in a DSS notebook _(for simplicity but it make no sense to provision stuff from DSS, its just easier to use the python API from there. Good enough for testing it)_
```
import dataiku
from dataiku import pandasutils as pdu
import pandas as pd
import dataikuapi
client = dataikuapi.FMClientAzure(host="http://localhost:10000", api_key_id="XXX", api_key_secret="XXX")
client.list_instances()
network = client.new_virtual_network_creator("test").with_azure_virtual_network("/subscriptions/8c59bf15-b4a9-4398-a354-d2a4e …
```
=> [sc-76604] Fix FM API for azure

dataikuapi/dss/tools/codegen.py, dataikuapi/dssclient.py
=> 9.0: import for ansible support

dataikuapi/dss_plugin_mlflow/__init__.py, dataikuapi/dss_plugin_mlflow/utils.py, dataikuapi/dssclient.py
Allow using the DSS MLflow plugin in an interactive way by using either:
```python
client = DSSClient(host, apiKey)
mlflow_handle = client.setup_mlflow("MYPROJECT")
mlflow = mlflow_handle.import_mlflow()  # this is optional, mlflow can be loaded as import mlflow
mlflow.log_metric...
mlflow_handle.clear()
```
or using a context manager
```python
client = DSSClient(host, apiKey)
with client.setup_mlflow("MYPROJECT") as mlflow:
mlflow.log_metric...
```
=> Refactor setup_mlflow contextmanager

dataikuapi/dss/project.py
Companion API PR of https://github.com/dataiku/dip/pull/14562
=> Add an unicity constraint on experiment name - API

dataikuapi/dss/project.py, dataikuapi/dss_plugin_mlflow/utils.py, dataikuapi/dssclient.py
On `feature/mlflow-experiment-tracking` this code will fail:
```python
from dataikuapi import DSSClient
import mlflow
import tempfile
client = DSSClient("http://localhost:8082", apiKey)
project = client.get_project("DEMOMLFLOW")
with client.setup_mlflow(project.project_key):
mlflow.log_artifact(tempfile.mkstemp()[1])
```
with:
```shell
~/devmisc/mlflow/mlflow/store/artifact/artifact_repository_registry.py in get_artifact_repository(self, artifact_uri)
68                 "Could not find a registered artifact repository for: {}. "
69                 "Currently registered schemes are: {}".format(
---> 70                     artifact_uri, list(self._registry.keys())
71                 )
72             )
MlflowException: Could not find a registered artifact repository for: …
```
=> Give MLflowHandle the ability to reload artifact_repository_registry

dataikuapi/dss/project.py, dataikuapi/dss/recipe.py
Companion test PR https://github.com/dataiku/dip/pull/14421
=> Added SER recipe creation

dataikuapi/dss/mlflow.py, dataikuapi/dss/project.py, dataikuapi/dssclient.py
This is the companion API of https://github.com/dataiku/dip/pull/14626#
=> Create dedicated class for MLflow custom endpoints

dataikuapi/apinode_admin_client.py
Python API part of the deploy anywhere feature: https://github.com/dataiku/dip/pull/14733
Adds a handler to the API node admin client to create code envs in the global cache of an API node.
See [ch75547](https://app.shortcut.com/dataiku/story/75547/base-docker-image-for-vertex-ai-prediction).
=> Deploy anywhere feature

dataikuapi/dss/savedmodel.py
In this PR, we add the support for the features_list argument for the set_core_metadata in the MLFLowVersionHandler.
**NB** : This PR is linked to https://github.com/dataiku/dip/pull/14866
=> MLFlowVersionHandler.set_core_metadata implement support for features_list

dataikuapi/dss/project.py, dataikuapi/dss_plugin_mlflow/artifact_repository.py, dataikuapi/dss_plugin_mlflow/header_provider.py, dataikuapi/dss_plugin_mlflow/utils.py
This is the companion PR of https://github.com/dataiku/dip/pull/15006
By setting the HTTP header ```x-dku-mlflow-managed-folder-id```, it allows the backend to prepare an artifact location URI containing the required managed folder id. This URI will be used as the base URI to store artifacts.
The TODO will be done as part of SC card 80078
=> Store the managed folder id in the MLflow artifact URI

dataikuapi/dss/ml.py
Companion dip PR https://github.com/dataiku/dip/pull/14999
```python
from dataikuapi import DSSClient
from sklearn import datasets
from sklearn import svm
import json
host = "http://localhost:8082/"
api_key = "kXxMvwMRvU2KoVqpCH47e0eoJ3GlJXWI"
project_key = "LOL"
client = DSSClient(host, api_key)
project = client.get_project(project_key)
task = project.get_ml_task("ptkvqn3M", "U1eqYF52")
trained_model = task.get_trained_model_details("A-LOL-ptkvqn3M-U1eqYF52-s2-pp1-m1")
response = trained_model.get_scoring_python_stream()
with open("~/Downloads/test.zip", "wb") as f:
f.write(response.content)
response = trained_model.get_scoring_python("~/Downloads/test_no_stream.zip")
```
=> Set get_scoring_python_stream

dataikuapi/dss/mlflow.py, dataikuapi/dss/project.py
Companion DIP PR: https://github.com/dataiku/dip/pull/15179
In addition to description in the companion PR: all new methods are added as Dataiku extensions to the standard MLflow Python API. Most of them correspond to endpoints defined in MLflow REST API, but available only through the CLI or the GUI, and not through the Python API:
- list_experiments
- rename_experiment
- restore_experiment
- restore_run
garbage_collect is not defined in the MLflow REST API but available through the CLI
list_models is a pure Dataiku extension.
clean_experiment_tracking_db is a nuclear bomb, usable only with admin rights, moved from project.py.
=> Complete MLflow REST API implementation

dataikuapi/dss/project.py, dataikuapi/dss_plugin_mlflow/utils.py
Stop creating managed folder automatically in setup_mlflow.
Tested manually and by running the integration/python/scenario/ml/prediction/mlflow/experiment_tracking/test_autolog.py test.
Related to:
- https://github.com/dataiku/dip/pull/15360
- https://github.com/dataiku/dku-contrib-private/pull/151
=> Dont auto create managed folder in setup_mlflow

dataikuapi/dss/dataset.py, dataikuapi/dss/feature_store.py, dataikuapi/dssclient.py
Companion dip PR: https://github.com/dataiku/dip/pull/15317
This PR adds the public python API of the feature store.
It introduces a `DSSFeatureStore` class, than can be instantiated through the api client, whose unique method allows to list feature groups.
It also add a read property and a method to `DSSDatasetSettings` to check if a dataset is a feature group and to promote (or downgrade) a dataset to the quality of feature group.
=> Feature store public API

dataikuapi/dss/recipe.py
This is related to the PR https://github.com/dataiku/dip/pull/15087
No change was required in the back-end to make moving a recipe possible, but I had to add the adequate function in the python API to make it convenient.
Doing this, I noticed that the `DSSProjectFlow::_to_smart_ref` function was broken for DSSRecipe inputs, so I added the id property.
=> Add move_to_zone function to the DSSRecipe

dataikuapi/dss_plugin_mlflow/utils.py
To test:
- build a kit with this branch
- edit make-studio-package.sh to set the API_CLIENT_VERSION to this branch name
- smtg like make && NOGEO=1 NOGEOIP=1 ./packagers/studio/make-studio-package.sh 11.0.0-20220410 ~/dss-releases
- install it
- test in a notebook (without encrypted RPC)
- enable encrypted RPC: ./bin/dssadmin install-encrypted-rpc
- test in a notebook
Simple code like:
```
import dataiku
import mlflow
import os
client = dataiku.api_client()
project = client.get_project("POUET")
mf = project.get_managed_folder("w6adRQEB")
#os.environ["MLFLOW_TRACKING_INSECURE_TLS"]="true"
project.setup_mlflow(managed_folder=mf)
with mlflow.start_run():
mlflow.log_param("alpha", 1)
mlflow.log_param("l1_ratio", 2)
mlflow.log_metric("rmse", 3)
mlflow.log_metric("r2", 4) …
```
=> Setting up connection for no verify and client certificate cases

dataikuapi/apinode_client.py, dataikuapi/base_client.py
Allowing to send a bearer token, so we can give a python sample code
=> [sc-72323] OAuth2 API node - Allow sending a bearer token

dataikuapi/dss/modelcomparison.py, dataikuapi/dss/modelevaluationstore.py, dataikuapi/fm/instancesettingstemplates.py, dataikuapi/fm/virtualnetworks.py
See [sc-85730](https://app.shortcut.com/dataiku/story/85730/absolute-imports-in-public-api-breaks-ansible-modules)
=> [sc85730] Make absolute imports relative

dataikuapi/dssclient.py
I didn't go very further in this ticket, as the 'architecture' type was already available in the REST API. It was really just a matter of exposing it to the python API.
=> [sc-80976] Add a parameter 'architecture' to the cluster create API

dataikuapi/dss/recipe.py
The no_fail argument was not passed to the stard_and_wait() method
=> bug fix : no_fail argument passed

dataikuapi/__init__.py, dataikuapi/fm/instances.py, dataikuapi/fm/instancesettingstemplates.py, dataikuapi/fm/tenant.py, dataikuapi/fm/virtualnetworks.py, dataikuapi/fmclient.py
[sc-85516]
use the associated PR in dataiku/dip, for the virtual network handling of default values
example
```
url = "https://gcp-fm-deploy"
key_id = "Mky3Q3pmLNdyxpTc"
key_secret = "OpZVEWNe1pJWQdZ0kPATKbn2aDsyFaSf"
client = dataikuapi.FMClientGCP(url, key_id, key_secret)
client._session.verify = None
istc = client.new_instance_template_creator("from api")
istc.with_ssh_key("ssh-rsa hohooho")
istc.with_block_project_wide_keys(False)
istc.with_restrict_metadata_server_access(True)
istc.with_runtime_service_account("foo@bar.com")
ist = istc.create()
ist.delete()
vnetc = client.new_virtual_network_creator("from api")
vnetc.with_default_values()
#vnetc.with_vpc("fchataigner-dev", "fm-network", "fm-subnetwork")
vnetc.with_network_tags("from", "api")
vnet = vnetc.create() …
```
=> client for FM on GCP

dataikuapi/dss/managedfolder.py, dataikuapi/dss_plugin_mlflow/artifact_repository.py
Changes
---------
-> Use PurePosixPath to manipulate paths in artifact folder on MLflow artifact_repository plugin
-> Make DSSManagedFolder.upload_folder work on windows
For this we used the string method replace to replace backslashes with normal slashes because
1. we work with relative path (so no prefix "C:/" for instance)
2. we don't know if pathlib is installed since we support python2.7 (whereas in the MLflow plugin part we need MLflow, hence python >= 3.6 where pathlib is builtin)
Testing
-------
Companion test PR: https://github.com/dataiku/dip/pull/17453 with the DOD there
To test on windows you can install the kit and directly edit the dataikuapi in the kit as suggested by @lpenet here: https://app.shortcut.com/dataiku/story/92017/experiment-tracking-does-not-work-on-windows
=> Path issue windows mlflow plugin

dataikuapi/dss_plugin_mlflow/utils.py
Prior to this, the following snippet was not working
1/ Create a folder named "Tracking" in DSS
2/ Execute in a notebook, using an MLflow enabled code env 
```
import dataiku
exp_tracking_folder = dataiku.Folder("Tracking") # looking by name, not id
exp_tracking_folder.get_info()
dataiku.api_client().get_default_project().setup_mlflow(managed_folder=exp_tracking_folder)
```
=> MlflowHandle with managed_folder.get_id() instead of name when it is a Folder

dataikuapi/dss/job.py
I actually did the math (and some live tests) because I thought a factor 2 was a bit too aggressive. And indeed, an unlucky job taking roughly 127 secondes will fall just after the polling request (between iter_5 and iter_6 in the first table below), and thus will gain an extra 124 seconds of waiting time... so almost 100﹪ extra time for a 2 minutes job. Here are tables with the waiting counter and the elapsed time.
1. before the fix, max at 300, factor 2
| iter | wait | elapsed |
|------|------|---------|
| 0    | 2    |       2 |
| 1    | 4    |       6 |
| 2    | 8    |      14 |
| 3    | 16   |      30 |
| 4    | 32   |      62 |
| 5    | 64   |     126 |
| 6    | 128  |     254 |
| 7    | 256  |     510 |
| 8    | 512  |    1022 |
| 9    | 300  |    1322 |
| 10   | 300  |    1622 | …
=> [sc-92338] smoother polling strategy

dataikuapi/fm/instances.py, dataikuapi/fm/virtualnetworks.py
add support for govern node creation
`
client = dataikuapi.FMClientAWS ("https://somewhere", "key", "secret")
client._session.verify = None
creator = client.new_virtual_network_creator ("MyNetwork")
creator.with_vpc ("vpc-xxx", "subnet-yyy")
netw = creator.create ()
netw.set_fleet_management (True, govern_server="Governor")
netw.save()
`
`
creator = client.new_instance_creator("MyGovernInstance", "ist-IJcznImxJFTI", "vn-xWfdn88cADov", "dss-11.0.2-default")
creator.with_dss_node_type(dataikuapi.fm.instances.FMNodeType.GOVERN).with_cloud_instance_type("m5a.2xlarge")
dss = creator.create ()
`
=> 99387 : support creating a govern node
