dataiku/dataiku-api-client-python

- dataikuapi/dss/scenario.py
- dataikuapi/dss/scenariorun.py
> some helper funcs on scenarios and runs

- dataikuapi/dss/wiki.py
[Cluhouse card](https://app.clubhouse.io/dataiku/story/41086/add-get-uploaded-file-to-python-client)
> Add get_uploaded_file to python client

- dataikuapi/dss/ml.py
- dataikuapi/utils.py
First implementation for subpopulation.
> Implement wrappers for post train computation results

- dataikuapi/dss/macro.py
- dataikuapi/dss/ml.py
- dataikuapi/dss/project.py
- dataikuapi/dss/scenario.py
- dataikuapi/dssclient.py
Mutable arguments were used as parameter to http requests. So they are "side effect" free wrt the runtime, but it is still better to avoid mutability
> style: make all mutable function arguments "None" and init in function body

- dataikuapi/dssclient.py
reduced version with only what's needed for webapp impersonation
> add proxy ticket call

- dataikuapi/dss/apideployer.py
[ch37697](https://app.clubhouse.io/dataiku/story/37697/improve-python-public-api-client-for-api-deployer)
https://github.com/dataiku/dip/pull/10420 should be merged first
> Add methods to delete infra / delete a node on static infra

- dataikuapi/apinode_client.py
⚠️ Merge https://github.com/dataiku/dip/pull/10362 at the same time
> Add explanations parameters to APINodeClient.predict_record(s)

- dataikuapi/apinode_client.py
To be merge with dataiku/dip#10638
> Increase MC steps max from 400 to 1000

- dataikuapi/dss/plugin.py
Companion PR of https://github.com/dataiku/dip/pull/10249
> Plugin uninstall - public API

- dataikuapi/dss/continuousactivity.py
- dataikuapi/dss/project.py
- dataikuapi/dss/recipe.py
- dataikuapi/dss/streaming_endpoint.py
> public api for streaming endpoints

- dataikuapi/dss/managedfolder.py
Rebirth of #80 
[ch50316](https://app.clubhouse.io/dataiku/story/50316)
> provide path to put_file to write in subfolder

- dataikuapi/dss/dataset.py
- dataikuapi/dss/flow.py
- dataikuapi/dss/managedfolder.py
- dataikuapi/dss/savedmodel.py
- dataikuapi/dss/streaming_endpoint.py
Add shared collection manipulation
Modification to take in account the streaming endpoints
[51916](https://app.clubhouse.io/dataiku/story/51916)
> Zones update after collection changes + small fixes

- dataikuapi/dss/ml.py
- dataikuapi/dss/tools/codegen.py
- dataikuapi/dss/wiki.py
Use raw strings which fixes some escape characters in a few patterns.
> regex: correctly escape patterns using raw strings

- dataikuapi/dss/flow.py
> Add Saved models and folders to flow read API 

- dataikuapi/dss/admin.py
[ch48537](https://app.clubhouse.io/dataiku/story/48537/expose-forcerebuildenv-option-in-code-envs-public-api)
> Adding force_rebuild_env param (default False) to DSSCodeEnv.update_packages

- dataikuapi/dss/sqlquery.py
- dataikuapi/dssclient.py
[ch46619](https://app.clubhouse.io/dataiku/story/46619/hiveexecutor-impalaexecutor-cannot-be-used-when-there-is-no-project-free-impersonation-rule)
This depends on: https://github.com/dataiku/dip/pull/11203
> fix impersonation also in public API

- dataikuapi/dss/ml.py
Add a helper to easily access and use Hints
> diagnostics: add helper in DSSTrainedModelDetails

- dataikuapi/dss/recipe.py
- dataikuapi/dss/tools/codegen.py
replacement of https://github.com/dataiku/dataiku-api-client-python/pull/105
> add fuzzy join recipe creator

- dataikuapi/dss/ml.py
[CH58082](https://app.clubhouse.io/dataiku/story/58082/ml-public-api-python-client-get-all-possible-algorithm-names-and-get-enabled-algorithm-names-are-broken-for-clustering-algorithms)
> Fix clustering mltask

- dataikuapi/dssclient.py
[ch55131](https://app.clubhouse.io/dataiku/story/55131/public-api-for-license)
To use with https://github.com/dataiku/dip/pull/11777
> Public api for license

- dataikuapi/dss/ml.py
[CH58931](https://app.clubhouse.io/dataiku/story/58931/public-api-python-client-helpers-for-time-based-ordering)
> Add time-based ordering helpers

- dataikuapi/dss/ml.py
[CH59982](https://app.clubhouse.io/dataiku/story/59982/public-api-python-client-add-cross-validation-seed-to-hyperparametersearchsettings)
> Add cross-validation seed 

- dataikuapi/dss/jupyternotebook.py
- dataikuapi/dss/project.py
- dataikuapi/dssclient.py
Normalize the API with up-to-date development standard.
> [Jupyter notebook] use "as_type" instead of "as_object"

- dataikuapi/dss/apiservice.py
- dataikuapi/dss/project.py
[ch61775]
See corresponding PR on dip: https://github.com/dataiku/dip/pull/12374
> Add publish version method

- dataikuapi/dss/future.py
Story details: [ch63638](https://app.clubhouse.io/dataiku/story/63638)
Repairing regression introduced  by https://github.com/dataiku/dataiku-api-client-python/commit/0be33c19afe178cb7c0be4a7eaeaa1dd34b87e14
> Repairing `DSSFuture.wait_for_result()`

- dataikuapi/dss/ml.py
[CH58941](https://app.clubhouse.io/dataiku/story/58941/public-api-python-client-add-syntactic-sugar-for-numericalhyperparametersettings)
> Add syntactic sugar for numerical hyperparameters

- dataikuapi/dss/modelevaluationstore.py
Companion of https://github.com/dataiku/dip/pull/12419
> Methods to query the metrics (as in DSS Metrics) of a MES or a ME

- dataikuapi/dss/recipe.py
> Added GeoJoin recipe API

- dataikuapi/dss/admin.py
- dataikuapi/dssclient.py
This reverts commit c17b7049b6af405830e3246d1d29899c5eeee3d6.
> Revert "[ch58209] Add personal API keys APIs"

- dataikuapi/dss/metrics.py
- dataikuapi/dss/modelevaluationstore.py
- dataikuapi/dss/project.py
[ch68817](https://app.clubhouse.io/dataiku/story/68817/refactor-the-public-api-for-model-evaluation-stores?vc_group_by=week&ct_workflow=all&cf_workflow=500000001)
See companion backend PR https://github.com/dataiku/dip/pull/13239 and https://github.com/dataiku/dip/pull/13215 which also trigered some changes.
> Refactoring the MES public API

- dataikuapi/dss/admin.py
- dataikuapi/dssclient.py
> improve api for code env settings

- dataikuapi/dss/savedmodel.py
Additions to the public API of MLFlow models, authored by @cstenac
Features:
- code env selection, per model version  
- a helper class to interact with MLFlow model metrics params
> Selectable code env for MLFlow models

- dataikuapi/dss/savedmodel.py
> Support DSSDataset or dataiku.Dataset in MLFlowVersionHandler.evaluate

- dataikuapi/dss/managedfolder.py
- dataikuapi/dss/savedmodel.py
Companion public API PR of https://github.com/dataiku/dip/pull/14090
* Add `DSSManagedFolder.upload_folder` as util to upload the whole content of a folder recursively into a path in the managed folder.
* Add `DSSSavedModel.import_mlflow_version_from_managed_folder`
> upload_folder function for managed folders

- dataikuapi/dss/project.py
- dataikuapi/dss_plugin_mlflow/artifact_repository.py
- dataikuapi/dss_plugin_mlflow/utils.py
- dataikuapi/dssclient.py
This is a WIP
V0 for the artifact plugin
> MLFlow plugin artifacts

- dataikuapi/dss/project.py
An integration test is going to be submitted shortly after this PR is merged.
At the moment, the integration test cannot run because of PythonContextSwitcher issues. However, the draft PR can be read at this location:
https://github.com/dataiku/dip/pull/14501
> Added a function to retrieve a model from a comparison

- dataikuapi/dss/project.py
Story details: https://app.shortcut.com/dataiku/story/76185
> Check server side that a MLflow saved model name is not empty when creating or updating

- dataikuapi/dss/managedfolder.py
- dataikuapi/dss/recipe.py
- dataikuapi/dss/savedmodel.py
Public python API changes related to the shortcut cards of the 10.0.3 - MLflow epic https://app.shortcut.com/dataiku/epic/74902?cf_workflow=500000001&vc_group_by=day&ct_workflow=all
Corresponding dip PR https://github.com/dataiku/dip/pull/14742
> MLflow for DSS 10.0.3

- dataikuapi/dss/flow.py
This PR goes to pair with https://github.com/dataiku/dip/pull/14461
> [sc-68952] Add items to zone by batch

- dataikuapi/dss/modelcomparison.py
- dataikuapi/dss/project.py
- dataikuapi/dss/recipe.py
Companion DIP PR https://github.com/dataiku/dip/pull/14825
> MES / MC updates

- dataikuapi/dss/apideployer.py
- dataikuapi/dss/projectdeployer.py
Update client to support bundle governance and related infrastructure settings
[sc-75824]
> Add support for bundle governance

- dataikuapi/dss/dataset.py
new public Python API to retrieve all the information about a dataset.
> [sc-80919] new PAPI - dataset get full info

- dataikuapi/dss/project.py
- dataikuapi/dss_plugin_mlflow/utils.py
Also supports dataiku.Folder, as I saw no reason why we were not doing it.
Companion PR: https://github.com/dataiku/dip/pull/16126
> Support passing the managed folder as an id or a Folder in setup_mlflow

- dataikuapi/dss_plugin_mlflow/artifact_repository.py
- dataikuapi/dss_plugin_mlflow/utils.py
Companion PR of https://github.com/dataiku/dip/pull/15891
* Fix and simplify the download_artifacts method
* Reset tracking_uri and end eventual run when calling `setup_mlflow`
> MLflow dss flavor

- dataikuapi/dss/ml.py
Companion PR of https://github.com/dataiku/dip/pull/16248
> Add MLflow export to DSSTrainedPredictionModelDetails

- dataikuapi/dss/admin.py
Also adds the new "force stop" option.
[sc-82511]
> Add k8s cluster actions

- dataikuapi/dss/flow.py
- dataikuapi/dss/ml.py
- dataikuapi/utils.py
[sc-83419]
Should be merged together with: dataiku/dip#16061
Public documentation: dataiku/dss-doc#723
> feat: FDG API

- dataikuapi/dss/admin.py
- dataikuapi/dssclient.py
This PR goes in pair with https://github.com/dataiku/dip/pull/15723
You will need to checkout this PR to run the integration tests of the other PR
> [sc58209] Add personal API keys APIs

- dataikuapi/dss/plugin.py
- dataikuapi/dss/project.py
Add project libraries methods in project object
Adapt the plugins client to be consistent with modification in the public API
See https://github.com/dataiku/dip/pull/17144 for details on the modifications to the public API
> [SC-93184] Create public API for project libraries

- dataikuapi/dss/apiservice.py
Companion API PR of https://github.com/dataiku/dip/pull/16247
> Add support for clustering model in API endpoint

- dataikuapi/dss/project.py
Add listing and importing ES indices via the public API.
Name spacing and the "tables" are kept for backward compatibility and to prevent adding another object (seen with @cstenac).
[sc-95861]
> dataset import: list and import elastic search indices

- dataikuapi/dss/dataset.py
Fix for https://dataiku.slack.com/archives/CGD1MMU3Z/p1659473878826259
> Add Azure Synapse to list of SQL types
